name: Fetch Spotify Data
on:
  workflow_dispatch:

jobs:
  update_spotify_playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
  
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install axios
          
      - name: Update Spotify Playlist
        run: |
          node .github/workflows/fetch_spotify_data.js
          
      - name: Readme Replacer - Readme-Workflows
        uses: Readme-Workflows/readme-replacer@v1.0.1
        with:
          TEMPLATE_FILE: ./TEMPLATE.md
          COMMIT_FILE: ./TEST.md
          CUSTOM_REPLACER_FILE: ./.github/Replacer.json
          
            
            
