name: Update Spotify Playlist
on:
  workflow_dispatch:

jobs:
  update_spotify_playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
  
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install express axios cors cookie-parser
          
      - name: Update Spotify Playlist
        env:
          SPOTIFY_ACCESS_TOKEN: ${{ secrets.SPOTIFY_ACCESS_TOKEN }}
        run: |
          node .github/workflows/update_spotify_playlist.js
            
            
