name: Update Spotify Playlist
on:
  workflow_dispatch:

jobs:
  update_spotify_playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
  
      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Update Spotify Playlist
        env:
          SPOTIFY_ACCESS_TOKEN: ${{ secrets.SPOTIFY_ACCESS_TOKEN }}
        run: |
          python update_spotify_playlist.py
            
            
